name: CI

on: [push]

jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Install dependancies
        run: yarn install

      - name: Run tests
        run: yarn test
